### PR TITLE
Fact check with google js

### PR DESCRIPTION
**Pull request by oxzoid**
created code for fact checking using fact checker google API,only useful for controversial facts doesn't answer questions like most sold album etc. basically checks facts but doesn't tell facts.It also provides the source with the evaluation of the checked fact.

### CODE REVIEW

**Review by Patryk-jpg — COMMENTED** [review]
Looks good to me (the model.js file, I don't know about register commands for sure)

**Comment by oxzoid** [comment]
Been a week,no reviews
pls review it

**Review by darkcount2011 — CHANGES_REQUESTED** [review]
Recommend leaving the commented stuff out, and if you do, ensure that the imports are also left out if unused for clean merge, don't want random code snippets floating around in the main branche! Make a different file out of that and don't commit that one, for example.

**Review by darkcount2011 — APPROVED** [review]
Looks good to me.

Any reason the test.js is removed, or was that for the removed code?

**Comment by oxzoid** [comment]
it was for the removed code.

**Comment by oxzoid** [comment]
one more review for the merge, should I merge it as u reviewed it pedro or should I wait for on more review @darkcount2011

**Review by Patryk-jpg — COMMENTED** [review]
I don't see anything wrong

**Comment by oxzoid** [comment]
ok then i am merging since i got 2 reviews

**Pull request merged**
